name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '10'  

    - name: Install dependencies
      run: npm install

   # - name: Run tests
    #  run: npm test  

    - name: Build project
      run: npm run build  

    - name: Deploy to Netlify
      env:
        NETLIFY_AUTH_TOKEN: ${nfp_4rBsXWaLrFaughVTJMfBfAhzvFA4rcDm043bN}
        NETLIFY_SITE_ID: ${3ef5b4e9-cb53-4b30-b4d1-b2a8677c5dde}
      run: |
        npm install -g netlify-cli
        netlify deploy --dir=build --prod --site $NETLIFY_SITE_ID

